CREATE OR REPLACE VIEW RETAIL_ANALYTICS.TESTS.TEST_FACT_ORDERS_UNIQUE_ORDER_ID AS
SELECT
  ORDER_ID,
  COUNT(*) AS CNT
FROM RETAIL_ANALYTICS.ANALYTICS.FACT_ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;
