CREATE OR REPLACE VIEW RETAIL_ANALYTICS.TESTS.TEST_FACT_ORDER_ITEMS_FK AS
SELECT
  i.ORDER_ID
FROM RETAIL_ANALYTICS.ANALYTICS.FACT_ORDER_ITEMS i
LEFT JOIN RETAIL_ANALYTICS.ANALYTICS.FACT_ORDERS o
  ON i.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_ID IS NULL;
