WITH results AS (

  SELECT
    'NOT_NULL_FACT_ORDERS_ORDER_ID' AS TEST_NAME,
    (SELECT COUNT(*) FROM RETAIL_ANALYTICS.TESTS.TEST_NOT_NULL_ORDER_ID) AS FAILED_ROWS

  UNION ALL
  SELECT
    'UNIQUE_FACT_ORDERS_ORDER_ID',
    (SELECT COUNT(*) FROM RETAIL_ANALYTICS.TESTS.TEST_FACT_ORDERS_UNIQUE_ORDER_ID)

  UNION ALL
  SELECT
    'VALID_FACT_ORDERS_STATUS',
    (SELECT COUNT(*) FROM RETAIL_ANALYTICS.TESTS.TEST_FACT_ORDERS_VALID_STATUS)

  UNION ALL
  SELECT
    'FK_FACT_ORDER_ITEMS_ORDER_ID',
    (SELECT COUNT(*) FROM RETAIL_ANALYTICS.TESTS.TEST_FACT_ORDER_ITEMS_FK)
)

SELECT
  TEST_NAME,
  FAILED_ROWS,
  CASE WHEN FAILED_ROWS = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
  CURRENT_TIMESTAMP() AS RUN_TS
FROM results
ORDER BY STATUS DESC, FAILED_ROWS DESC;
