-- sql/ops/watermarks.sql
-- Stores incremental load watermarks per pipeline/table

CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYTICS.OPS;

CREATE TABLE IF NOT EXISTS RETAIL_ANALYTICS.OPS.WATERMARKS (
  PIPELINE_NAME STRING,
  TARGET_TABLE  STRING,
  WATERMARK_COL STRING,
  LAST_WATERMARK TIMESTAMP_NTZ,
  UPDATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed one watermark for FACT_ORDERS incremental load
MERGE INTO RETAIL_ANALYTICS.OPS.WATERMARKS t
USING (
  SELECT
    'FACT_ORDERS_LOAD' AS PIPELINE_NAME,
    'RETAIL_ANALYTICS.ANALYTICS.FACT_ORDERS' AS TARGET_TABLE,
    'ORDER_PURCHASE_TS' AS WATERMARK_COL,
    TO_TIMESTAMP_NTZ('1900-01-01') AS LAST_WATERMARK
) s
ON t.PIPELINE_NAME = s.PIPELINE_NAME
WHEN NOT MATCHED THEN
  INSERT (PIPELINE_NAME, TARGET_TABLE, WATERMARK_COL, LAST_WATERMARK)
  VALUES (s.PIPELINE_NAME, s.TARGET_TABLE, s.WATERMARK_COL, s.LAST_WATERMARK);
