-- Load RAW tables from Snowflake stage
-- Uses explicit FILES matching to avoid path ambiguity

COPY INTO RETAIL_ANALYTICS.RAW.RAW_ORDERS
FROM @RETAIL_ANALYTICS.RAW.STG_OLIST
FILE_FORMAT = (FORMAT_NAME = RETAIL_ANALYTICS.RAW.FF_CSV)
FILES = ('olist_orders_dataset.csv')
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RETAIL_ANALYTICS.RAW.RAW_CUSTOMERS
FROM @RETAIL_ANALYTICS.RAW.STG_OLIST
FILE_FORMAT = (FORMAT_NAME = RETAIL_ANALYTICS.RAW.FF_CSV)
FILES = ('olist_customers_dataset.csv')
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RETAIL_ANALYTICS.RAW.RAW_ORDER_ITEMS
FROM @RETAIL_ANALYTICS.RAW.STG_OLIST
FILE_FORMAT = (FORMAT_NAME = RETAIL_ANALYTICS.RAW.FF_CSV)
FILES = ('olist_order_items_dataset.csv')
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RETAIL_ANALYTICS.RAW.RAW_ORDER_PAYMENTS
FROM @RETAIL_ANALYTICS.RAW.STG_OLIST
FILE_FORMAT = (FORMAT_NAME = RETAIL_ANALYTICS.RAW.FF_CSV)
FILES = ('olist_order_payments_dataset.csv')
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RETAIL_ANALYTICS.RAW.RAW_PRODUCTS
FROM @RETAIL_ANALYTICS.RAW.STG_OLIST
FILE_FORMAT = (FORMAT_NAME = RETAIL_ANALYTICS.RAW.FF_CSV)
FILES = ('olist_products_dataset.csv')
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

COPY INTO RETAIL_ANALYTICS.RAW.RAW_SELLERS
FROM @RETAIL_ANALYTICS.RAW.STG_OLIST
FILE_FORMAT = (FORMAT_NAME = RETAIL_ANALYTICS.RAW.FF_CSV)
FILES = ('olist_sellers_dataset.csv')
ON_ERROR = 'CONTINUE'
FORCE = TRUE;
