CREATE OR REPLACE TABLE RETAIL_ANALYTICS.ANALYTICS.DIM_DATE AS
WITH dates AS (
  SELECT DATEADD(day, seq4(), '2016-01-01'::DATE) AS date_day
  FROM TABLE(GENERATOR(ROWCOUNT => 2000))
)
SELECT
  date_day AS date_key,
  YEAR(date_day) AS year,
  MONTH(date_day) AS month,
  DAY(date_day) AS day,
  DAYOFWEEK(date_day) AS day_of_week,
  WEEKOFYEAR(date_day) AS week_of_year
FROM dates;

CREATE OR REPLACE TABLE RETAIL_ANALYTICS.ANALYTICS.DIM_CUSTOMER AS
SELECT * FROM RETAIL_ANALYTICS.STAGING.STG_CUSTOMERS;

CREATE OR REPLACE TABLE RETAIL_ANALYTICS.ANALYTICS.DIM_PRODUCT AS
SELECT * FROM RETAIL_ANALYTICS.STAGING.STG_PRODUCTS;

CREATE OR REPLACE TABLE RETAIL_ANALYTICS.ANALYTICS.DIM_SELLER AS
SELECT * FROM RETAIL_ANALYTICS.STAGING.STG_SELLERS;
