-- sql/analytics/fact_orders_incremental.sql
-- Incremental load into FACT_ORDERS using MERGE + watermark

BEGIN;

-- 1) Ensure target exists (run your existing CTAS once beforehand OR create a minimal table)
-- Assumption: RETAIL_ANALYTICS.ANALYTICS.FACT_ORDERS already exists.

-- 2) Read watermark
WITH wm AS (
  SELECT LAST_WATERMARK AS last_wm
  FROM RETAIL_ANALYTICS.OPS.WATERMARKS
  WHERE PIPELINE_NAME = 'FACT_ORDERS_LOAD'
),

src AS (
  SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.ORDER_STATUS,
    o.ORDER_PURCHASE_TS,
    o.ORDER_APPROVED_TS,
    o.ORDER_DELIVERED_CARRIER_TS,
    o.ORDER_DELIVERED_CUSTOMER_TS,
    o.ORDER_ESTIMATED_DELIVERY_DATE
  FROM RETAIL_ANALYTICS.STAGING.STG_ORDERS o
  CROSS JOIN wm
  WHERE o.ORDER_PURCHASE_TS > wm.last_wm
)

MERGE INTO RETAIL_ANALYTICS.ANALYTICS.FACT_ORDERS t
USING src s
ON t.ORDER_ID = s.ORDER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = s.CUSTOMER_ID,
  ORDER_STATUS = s.ORDER_STATUS,
  ORDER_PURCHASE_TS = s.ORDER_PURCHASE_TS,
  ORDER_APPROVED_TS = s.ORDER_APPROVED_TS,
  ORDER_DELIVERED_CARRIER_TS = s.ORDER_DELIVERED_CARRIER_TS,
  ORDER_DELIVERED_CUSTOMER_TS = s.ORDER_DELIVERED_CUSTOMER_TS,
  ORDER_ESTIMATED_DELIVERY_DATE = s.ORDER_ESTIMATED_DELIVERY_DATE
WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_PURCHASE_TS,
  ORDER_APPROVED_TS, ORDER_DELIVERED_CARRIER_TS,
  ORDER_DELIVERED_CUSTOMER_TS, ORDER_ESTIMATED_DELIVERY_DATE
) VALUES (
  s.ORDER_ID, s.CUSTOMER_ID, s.ORDER_STATUS, s.ORDER_PURCHASE_TS,
  s.ORDER_APPROVED_TS, s.ORDER_DELIVERED_CARRIER_TS,
  s.ORDER_DELIVERED_CUSTOMER_TS, s.ORDER_ESTIMATED_DELIVERY_DATE
);

-- 3) Update watermark to max loaded ts from staging (only if new rows loaded)
UPDATE RETAIL_ANALYTICS.OPS.WATERMARKS
SET LAST_WATERMARK = (
  SELECT COALESCE(MAX(ORDER_PURCHASE_TS), LAST_WATERMARK)
  FROM RETAIL_ANALYTICS.STAGING.STG_ORDERS
),
UPDATED_AT = CURRENT_TIMESTAMP()
WHERE PIPELINE_NAME = 'FACT_ORDERS_LOAD';

COMMIT;
